development:
  host: 'http://454f3ca3.ngrok.io'
  github_token: 3540517114dc92a4cc03
  github_secret: 3c739428390cbffa9e1adc8daf98d78fbf52932f
  secret_key_base: cc684a489e2a55acbe85b286ca93add33b96a3f98a62b0a11db5e979a0886fb55282de8d999bd2cf91ece95b2b35cf44af1c7a1804f0fb0845f7d3997fd0e175

test:
  secret_key_base: 2e0a1f1917132dab8e3c5605dc3e001baedb32040a1557d9b76e8deda5a6431c26c96370d5359d245d50e522aab8794915c8426aa78656381d11c67bd49413e3

production:
  host: <%= ENV['HOST'] %>
  github_token: <%= ENV['GITHUB_TOKEN'] %>
  github_secret: <%= ENV['GITHUB_SECRET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
